services:
  library-backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 8080
    environment:
      - DB_HOST=${mysql-1775a47d-librarypro.i.aivencloud.com}
      - DB_PORT=${21348}
      - DB_NAME=${defaultdb}
      - DB_USER=${avnadmin}
      - DB_PASSWORD=${AVNS_JY_rBnD3mUceSoAiDbe}
